apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
